Document: slowmovideo
Title: Debian slowmovideo Manual
Author: <insert document author here>
Abstract: This manual describes what slowmovideo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/slowmovideo/slowmovideo.sgml.gz

Format: postscript
Files: /usr/share/doc/slowmovideo/slowmovideo.ps.gz

Format: text
Files: /usr/share/doc/slowmovideo/slowmovideo.text.gz

Format: HTML
Index: /usr/share/doc/slowmovideo/html/index.html
Files: /usr/share/doc/slowmovideo/html/*.html
